### ISSUE TITLE
Requirements file too large

### ISSUE THREAD

**Issue by the-Minister-0001** [JoshuaKasa/DASO#1]
Your requirements.txt file seems to include a lot more than is necessary. There's no reason, for example, to install numpy or matplotlib.

I was able to start the script using the following requirements:
```
anyio==4.2.0
certifi==2023.11.17
colorama==0.4.6
exceptiongroup==1.2.0
h11==0.14.0
httpcore==1.0.2
httpx==0.26.0
idna==3.6
keyboard==0.13.5
markdown-it-py==3.0.0
mdurl==0.1.2
prompt-toolkit==3.0.36
Pygments==2.17.2
python-vlc==3.0.20123
pytube==15.0.0
questionary==2.0.1
rich==13.7.0
sniffio==1.3.0
tqdm==4.66.1
typing_extensions==4.9.0
wcwidth==0.2.13
youtube-search-python==1.6.6
```

**Comment by JoshuaKasa** [comment]
I know lmao, but I don't know how to make a requirements file with only the libraries of a single projects instead of all libraries I got installed.

Would you prefer to contribute yourself from a pull request or do you want me to do it myself? Thanks btw!
